export const MessageChannel = Object.freeze({
  FROM_INJECTED_TO_SERVICE: 0,
  FROM_CONTENT_TO_SERVICE: 1,
  FROM_SERVICE_TO_WORKER: 2,
  FROM_WORKER_TO_SERVICE: 3,
  FROM_PAGE_TO_CONTENT: 4,
  FROM_CONTENT_TO_PAGE: 5,
  FROM_SERVICE_TO_CONTENT: 6,
  FROM_SERVICE_TO_INJECTED: 7,
  FROM_SERVICE_TO_SERVICE: 8,
});
